//
//  MainPageProtocols.swift
//  clockInOut
//
//  Created armyxx on 2/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: Wireframe -
protocol MainPageWireframeProtocol: class {

}
//MARK: Presenter -
protocol MainPagePresenterProtocol: class {
    func getDateTime()
    func getClockIn()
    func getClockOut()
    func notifySuccessAlert(message: String)
    func getBackGroundColor(color: UIColor)
}

//MARK: Interactor -
protocol MainPageInteractorProtocol: class {

    var presenter: MainPagePresenterProtocol?  { get set }
    func setClockIn()
    func setClockOut()
}

//MARK: View -
protocol MainPageViewProtocol: class {

    var presenter: MainPagePresenterProtocol?  { get set }
    func showDateTime(currentDate: String, currentTime: String)
    func showSuccessAlert(message: String)
    func changeBackgroundColor(color: UIColor)
}
