//
//  MainPagePresenter.swift
//  clockInOut
//
//  Created armyxx on 2/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainPagePresenter: MainPagePresenterProtocol {

    weak private var view: MainPageViewProtocol?
    var interactor: MainPageInteractorProtocol?
    private let router: MainPageWireframeProtocol

    init(interface: MainPageViewProtocol, interactor: MainPageInteractorProtocol?, router: MainPageWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func notifyRouteLogin() {
        self.router.routeToLoginPage()
    }
}
