//
//  MainPageViewController.swift
//  clockInOut
//
//  Created armyxx on 2/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Firebase
import FirebaseAuth

class MainPageViewController: UIViewController, MainPageViewProtocol {

	var presenter: MainPagePresenterProtocol?

    @IBOutlet weak var logoutButton: UIButton!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Main"
        if #available(iOS 13.0, *) {
            navigationController?.navigationBar.backgroundColor = .secondarySystemBackground
        } else {
            navigationController?.navigationBar.backgroundColor = .white
        }
    }
    
    @IBAction func didTapLogout(_ sender: UIButton) {
        do {
            try FirebaseAuth.Auth.auth().signOut()
            print("singed out")
            UserDefaults.standard.set(false, forKey: "checkLogin")
            self.presenter?.notifyRouteLogin()
        }
        catch {
            print("Something went wrong")
        }
    }
}


