//
//  MainPageViewController.swift
//  clockInOut
//
//  Created armyxx on 2/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainPageViewController: UIViewController, MainPageViewProtocol {

	var presenter: MainPagePresenterProtocol?
    
    @IBOutlet weak var timeLabel: UILabel!
    @IBOutlet weak var dateLabel: UILabel!
    @IBOutlet weak var indicator: UIActivityIndicatorView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Main"
        if #available(iOS 13.0, *) {
            navigationController?.navigationBar.backgroundColor = .secondarySystemBackground
        } else {
            navigationController?.navigationBar.backgroundColor = .white
        }
        
        self.showLoader()
        self.presenter?.getDateTime()
    }
    
    func showLoader() {
        indicator.color = .systemRed
        indicator.startAnimating()
    }
    
    func showDateTime(currentDate: String, currentTime: String) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5, execute: {
            self.indicator.stopAnimating()
            self.indicator.hidesWhenStopped = true
            self.timeLabel.text = currentTime
            self.dateLabel.text = currentDate
        })
    }
}


