//
//  HistoryPageProtocols.swift
//  clockInOut
//
//  Created armyxx on 20/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HistoryPageWireframeProtocol: class {

}
//MARK: Presenter -
protocol HistoryPagePresenterProtocol: class {
    func notifyHistoryData()
    func getHistoryData(dataHistory: [DataHistory])
}

//MARK: Interactor -
protocol HistoryPageInteractorProtocol: class {

    var presenter: HistoryPagePresenterProtocol?  { get set }
    func setDataHistory()
}

//MARK: View -
protocol HistoryPageViewProtocol: class {

    var presenter: HistoryPagePresenterProtocol?  { get set }
    func showDataHistory(dataHistory: [DataHistory])
}
