//
//  HistoryPageViewController.swift
//  clockInOut
//
//  Created armyxx on 20/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPageViewController: UIViewController, HistoryPageViewProtocol {

	var presenter: HistoryPagePresenterProtocol?
    var dataHistory: [DataHistory] = []

    @IBOutlet weak var navBarHistory: UINavigationBar!
    @IBOutlet weak var tableView: UITableView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "History"
        
        if #available(iOS 13.0, *) {
            navBarHistory.barTintColor = .secondarySystemBackground
        } else {
            navBarHistory.barTintColor = .white
        }
        
        tableView.register(HistoryTableViewCell.nib(), forCellReuseIdentifier: "HistoryTableViewCell")
        tableView.delegate = self
        tableView.dataSource = self
        navBarHistory.delegate = self
        self.presenter?.notifyHistoryData()
    }
    
    func showDataHistory(dataHistory: [DataHistory]) {
        self.dataHistory = dataHistory
        DispatchQueue.main.async {
            self.tableView.reloadData()
        }
    }
    
    func showErrorAlert(error: Error?) {
        guard error == nil else {
            let alertController = UIAlertController(title: "Someting Wrong",
                                                    message: "\(error!.localizedDescription)",
                                                    preferredStyle: .alert)
            
            let okAction = UIAlertAction(title: "OK",
                                             style: .cancel,
                                             handler: nil)
            
            alertController.addAction(okAction)
            self.present(alertController, animated: true, completion: nil)
            return
        }
    }

}

extension HistoryPageViewController: UINavigationBarDelegate {
    
    func position(for bar: UIBarPositioning) -> UIBarPosition {
        return .topAttached
    }
}

extension HistoryPageViewController: UITableViewDelegate {
    
}

extension HistoryPageViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return dataHistory.count
    }
    
    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return "History of Clock in - out"
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: HistoryTableViewCell.identifier, for: indexPath) as! HistoryTableViewCell
        
        cell.configure(with: dataHistory[indexPath.item])
 
        return cell
    }
}
