//
//  LoginPageProtocols.swift
//  clockInOut
//
//  Created armyxx on 1/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoginPageWireframeProtocol: class {
    func tabBarViewController()
}
//MARK: Presenter -
protocol LoginPagePresenterProtocol: class {
    func notifyViewRouteMainPage()
}

//MARK: Interactor -
protocol LoginPageInteractorProtocol: class {

    var presenter: LoginPagePresenterProtocol?  { get set }
}

//MARK: View -
protocol LoginPageViewProtocol: class {

    var presenter: LoginPagePresenterProtocol?  { get set }
}
