//
//  LoginPageRouter.swift
//  clockInOut
//
//  Created armyxx on 1/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginPageRouter: LoginPageWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    func routeToMainPage() {
        let mainPage = MainPageRouter.createModule()
        
        mainPage.modalPresentationStyle = .fullScreen
        self.viewController?.present(mainPage, animated: true, completion: nil)
    }
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LoginPageViewController(nibName: nil, bundle: nil)
        let interactor = LoginPageInteractor()
        let router = LoginPageRouter()
        let presenter = LoginPagePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return UINavigationController(rootViewController: view)
    }
}
