//
//  LoginPageRouter.swift
//  clockInOut
//
//  Created armyxx on 1/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginPageRouter: LoginPageWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    func routeToSignUp() {
        let viewControllerSignUpPage = RegisterPageRouter.createModule()
        
        viewControllerSignUpPage.modalPresentationStyle = .fullScreen;
        self.viewController?.present(viewControllerSignUpPage, animated: true)
    }
    
    func tabBarViewController() {
        let viewControllerTabBar = UITabBarController()
        let viewControllerMainPage = MainPageRouter.createModule()
        let viewControllerMenuPage = MenuPageRouter.createModule()
        
        viewControllerMainPage.title = "Main"
        viewControllerMenuPage.title = "Menu"
        
        if #available(iOS 13.0, *) {
            viewControllerTabBar.tabBar.backgroundColor = .secondarySystemBackground
        } else {
            viewControllerTabBar.tabBar.backgroundColor = .white
        }
        
        viewControllerTabBar.setViewControllers([viewControllerMainPage, viewControllerMenuPage], animated: false)
        
        guard let items = viewControllerTabBar.tabBar.items else {
            return
        }
        
        let images = ["clock", "text.justify"]
        
        for x in 0..<items.count {
            items[x].image = UIImage(systemName: images[x])
        }
        
        viewControllerTabBar.modalPresentationStyle = .fullScreen;
        self.viewController?.present(viewControllerTabBar, animated: true)
        
    }
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LoginPageViewController(nibName: nil, bundle: nil)
        let interactor = LoginPageInteractor()
        let router = LoginPageRouter()
        let presenter = LoginPagePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return UINavigationController(rootViewController: view)
    }
}
