//
//  ProfilePageProtocols.swift
//  clockInOut
//
//  Created armyxx on 17/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ProfilePageWireframeProtocol: class {
    
    func backToMenu()
}
//MARK: Presenter -
protocol ProfilePagePresenterProtocol: class {
    
    func notifyRouteMenu()
    func notifyDataFromFirestore()
    func getDataFromFirestore(firstname: String, lastname: String, uid: String)
    func notifyResetPassword(email: String)
    func notifySuccessAlert(message: String)
    func notifyErrorAlert(error: Error?)
}

//MARK: Interactor -
protocol ProfilePageInteractorProtocol: class {

    var presenter: ProfilePagePresenterProtocol?  { get set }
    func setDataFromFirestore()
    func resetPassword(email: String)
}

//MARK: View -
protocol ProfilePageViewProtocol: class {

    var presenter: ProfilePagePresenterProtocol?  { get set }
    func showUserData(firstname: String, lastname: String, uid: String)
    func showSuccessAlert(message: String)
    func showErrorAlert(error: Error?)
}
