//
//  ProfilePageRouter.swift
//  clockInOut
//
//  Created armyxx on 17/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfilePageRouter: ProfilePageWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    func backToMenu() {
        self.viewController?.dismiss(animated: true, completion: nil)
    }
    
    func routeToLoginPage() {
        let loginPage = LoginPageRouter.createModule()
        
        loginPage.modalPresentationStyle = .fullScreen
        self.viewController?.present(loginPage, animated: true, completion: nil)
    }
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ProfilePageViewController(nibName: nil, bundle: nil)
        let interactor = ProfilePageInteractor()
        let router = ProfilePageRouter()
        let presenter = ProfilePagePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
     
        return UINavigationController(rootViewController: view)
    }
}
