//
//  ProfilePageProtocols.swift
//  clockInOut
//
//  Created armyxx on 17/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: Wireframe -
protocol ProfilePageWireframeProtocol: class {
    
    func backToMenu()
    func routeToLoginPage()
}
//MARK: Presenter -
protocol ProfilePagePresenterProtocol: class {
    
    func notifyRouteMenu()
    func notifyDataFromFirestore()
    func getDataFromFirestore(firstname: String, lastname: String, uid: String)
    func notifyResetPassword(email: String)
    func notifyConfirmDelete(confirmDelete: String)
    func notifyAlert(title:String, message: String)
    func notifyErrorAlert(error: Error?)
    func notifyRouteLogin()
    func notifyDeleteSuccessAlert(title:String, message: String)
    func getLogout()
    func getProfileImage(image_profile: String)
    func notifyProfileImage()
    func notifyUploadImage(image_profile: UIImage?)
}

//MARK: Interactor -
protocol ProfilePageInteractorProtocol: class {

    var presenter: ProfilePagePresenterProtocol?  { get set }
    func setDataFromFirestore()
    func resetPassword(email: String)
    func deleteUser(confirmDelete: String)
    func setLogoutAfterDeleteUserData()
    func dowloadProfileImage()
    func uploadProfileImage(image_profile: UIImage?)
}

//MARK: View -
protocol ProfilePageViewProtocol: class {

    var presenter: ProfilePagePresenterProtocol?  { get set }
    func showUserData(firstname: String, lastname: String, uid: String)
    func showAlert(title: String, message: String)
    func showDeleteSuccessAlert(title: String, message: String)
    func showErrorAlert(error: Error?)
    func showProfileImage(image_profile: String)
}
