//
//  ForgetPasswordPageProtocols.swift
//  clockInOut
//
//  Created armyxx on 2/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ForgetPasswordPageWireframeProtocol: class {

}
//MARK: Presenter -
protocol ForgetPasswordPagePresenterProtocol: class {

}

//MARK: Interactor -
protocol ForgetPasswordPageInteractorProtocol: class {

  var presenter: ForgetPasswordPagePresenterProtocol?  { get set }
}

//MARK: View -
protocol ForgetPasswordPageViewProtocol: class {

  var presenter: ForgetPasswordPagePresenterProtocol?  { get set }
}
