//
//  MenuPageProtocols.swift
//  clockInOut
//
//  Created armyxx on 13/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MenuPageWireframeProtocol: class {
    func routeToLoginPage()
}
//MARK: Presenter -
protocol MenuPagePresenterProtocol: class {
    
    func notifyRouteLogin()
    func notifyLogout()
}

//MARK: Interactor -
protocol MenuPageInteractorProtocol: class {

    var presenter: MenuPagePresenterProtocol?  { get set }
    func doLogout()
}

//MARK: View -
protocol MenuPageViewProtocol: class {

    var presenter: MenuPagePresenterProtocol?  { get set }
}
