//
//  MenuPageViewController.swift
//  clockInOut
//
//  Created armyxx on 13/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MenuPageViewController: UIViewController, MenuPageViewProtocol {

	var presenter: MenuPagePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Menu"
        if #available(iOS 13.0, *) {
            navigationController?.navigationBar.backgroundColor = .secondarySystemBackground
        } else {
            navigationController?.navigationBar.backgroundColor = .white
        }
    }

}
