//
//  MenuPageRouter.swift
//  clockInOut
//
//  Created armyxx on 13/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MenuPageRouter: MenuPageWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    func routeToLoginPage() {
        let loginPage = LoginPageRouter.createModule()
        
        loginPage.modalPresentationStyle = .fullScreen
        self.viewController?.present(loginPage, animated: true, completion: nil)
    }
    
    func routeToProfile() {
        let profilePageNavigator = ProfilePageRouter.createModule()
        
        profilePageNavigator.modalPresentationStyle = .fullScreen
        self.viewController?.present(profilePageNavigator, animated: true, completion: nil)
        
//        profilePageNavigator.modalPresentationStyle = .fullScreen
//        self.viewController?.navigationController?.pushViewController(profilePageNavigator, animated: true)
    }
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MenuPageViewController(nibName: nil, bundle: nil)
        let interactor = MenuPageInteractor()
        let router = MenuPageRouter()
        let presenter = MenuPagePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
