//
//  MenuPageInteractor.swift
//  clockInOut
//
//  Created armyxx on 13/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MenuPageInteractor: MenuPageInteractorProtocol {

    weak var presenter: MenuPagePresenterProtocol?
}
