//
//  LaunchPageInteractor.swift
//  clockInOut
//
//  Created armyxx on 1/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LaunchPageInteractor: LaunchPageInteractorProtocol {

    weak var presenter: LaunchPagePresenterProtocol?
}
