//
//  LaunchPagePresenter.swift
//  clockInOut
//
//  Created armyxx on 1/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LaunchPagePresenter: LaunchPagePresenterProtocol {

    weak private var view: LaunchPageViewProtocol?
    var interactor: LaunchPageInteractorProtocol?
    private let router: LaunchPageWireframeProtocol

    init(interface: LaunchPageViewProtocol, interactor: LaunchPageInteractorProtocol?, router: LaunchPageWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func notifyRouteLoginPage() {
        DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(2), execute: {
            if UserDefaults.standard.bool(forKey: "checkLogin") == false {
                self.router.routeToLogin()
            } else {
                self.router.routeToMain()
            }
        })
    }
}
