//
//  LaunchPageViewController.swift
//  clockInOut
//
//  Created armyxx on 1/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LaunchPageViewController: UIViewController, LaunchPageViewProtocol {

	var presenter: LaunchPagePresenterProtocol?

    @IBOutlet weak var indicator: UIActivityIndicatorView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let backgroundImage = UIImageView(frame: UIScreen.main.bounds)
        backgroundImage.image = UIImage(named: "backgroundClock")
        backgroundImage.contentMode = .scaleAspectFill
        
        self.view.insertSubview(backgroundImage, at: 0)
        self.showLoader()
        self.presenter?.notifyRouteLoginPage()
    }
    
    func showLoader() {
        indicator.color = .white
        indicator.startAnimating()
    }
}
