//
//  LaunchPageRouter.swift
//  clockInOut
//
//  Created armyxx on 1/12/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LaunchPageRouter: LaunchPageWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    func routeToLogin() {
        let loginPage = LoginPageRouter.createModule()
        
        loginPage.modalPresentationStyle = .fullScreen
        self.viewController?.present(loginPage, animated: true)
    }
    
    func routeToMain() {
        let MainPage = MainPageRouter.createModule()
        
        MainPage.modalPresentationStyle = .fullScreen
        self.viewController?.present(MainPage, animated: true)
    }
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LaunchPageViewController(nibName: nil, bundle: nil)
        let interactor = LaunchPageInteractor()
        let router = LaunchPageRouter()
        let presenter = LaunchPagePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
